(()=>{
const data=window.STOTEN_COMPARE_DATA; const all=data.items;
const state={type:'rubber',selected:[]};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const max={rubber:{speed:180,spin:140,control:150},blade:{speed:140,control:135,weight:110}};
const labels={speed:'Rýchlosť',spin:'Rotácia',control:'Kontrola',weight:'Hmotnosť'};
const colors={speed:'speed',spin:'spin',control:'control',weight:'weight'};
const fmt=v=>v==null?'—':String(v).replace('.',',');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=(v,c='EUR')=>v==null?'—':new Intl.NumberFormat('sk-SK',{style:'currency',currency:c}).format(v);
function score(item){const keys=item.type==='rubber'?['speed','spin','control']:['speed','control'];const pairs=keys.map(k=>[k,item.metrics[k]]).filter(([,v])=>typeof v==='number');if(!pairs.length)return 0;return Math.round(pairs.reduce((a,[k,v])=>a+(v/max[item.type][k])*100,0)/pairs.length)}
function segments(v,key,type){const count=16,on=v==null?0:Math.max(0,Math.min(count,Math.round(v/max[type][key]*count)));return `<div class="segments">${Array.from({length:count},(_,i)=>`<i class="seg ${i<on?'on '+colors[key]:''}"></i>`).join('')}</div>`}
function norm(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}function urlPath(s){try{return new URL(s,location.origin).pathname.replace(/\/+$/,'').toLowerCase()}catch{return ''}}function params(){const p=new URLSearchParams(location.search);const type=p.get('type');state.type=(type==='dreva'||type==='blade')?'blade':'rubber';const ids=(p.get('ids')||'').split(',').filter(Boolean);state.selected=ids.map(id=>all.find(x=>x.id===id)).filter(x=>x&&x.type===state.type).slice(0,5);const add=p.get('add');const sourceUrl=p.get('url');if(add||sourceUrl){const n=norm(decodeURIComponent(add||''));const wantedPath=urlPath(decodeURIComponent(sourceUrl||''));const match=(wantedPath?all.find(x=>x.type===state.type&&urlPath(x.url)===wantedPath):null)||all.find(x=>x.type===state.type&&(x.id===add||norm(x.name)===n))||all.find(x=>x.type===state.type&&n&&(norm(x.name).includes(n)||n.includes(norm(x.name))));if(match&&!state.selected.some(x=>x.id===match.id)&&state.selected.length<5)state.selected.push(match)}if(!state.selected.length){const wanted=state.type==='rubber'?['Evolution MX-P','Dynaryz ACC','Rakza 7']:['Stratus Power Wood','Cybershape Carbon','Timo Boll ALC'];for(const q of wanted){const x=all.find(i=>i.type===state.type&&i.inOffer&&i.name.toLowerCase().includes(q.toLowerCase()));if(x&&!state.selected.some(y=>y.id===x.id))state.selected.push(x)}if(state.selected.length<2)state.selected.push(...all.filter(i=>i.type===state.type&&i.inOffer&&!state.selected.some(y=>y.id===i.id)).slice(0,3-state.selected.length))}}
function syncUrl(replace=true){const p=new URLSearchParams();p.set('type',state.type==='rubber'?'potahy':'dreva');if(state.selected.length)p.set('ids',state.selected.map(x=>x.id).join(','));const search='?'+p.toString();history[replace?'replaceState':'pushState']({},'',location.pathname+search);if(window.parent!==window)window.parent.postMessage({type:'stotenCompareState',search},'*')}
function render(){ $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.type===state.type)); $('#selectedCount').textContent=`${state.selected.length} / 5`;renderCards();renderRanking();renderTable();syncUrl(); }
function renderCards(){const area=$('#selectionArea');let html=state.selected.map(card).join('');if(state.selected.length<5)html+=`<button class="add-card" id="addCard"><div><div class="add-plus">+</div><h3>Pridať produkt</h3><p>Môžete pridať ešte ${5-state.selected.length} ${5-state.selected.length===1?'produkt':'produkty'}</p></div></button>`;if(!state.selected.length)html=`<div class="empty-state"><h2>Začnite výberom produktu</h2><p>Na porovnanie potrebujete aspoň dva produkty.</p><button class="tab active" id="emptyAdd">Pridať produkt</button></div>`;area.innerHTML=html;$('#addCard')?.addEventListener('click',openPicker);$('#emptyAdd')?.addEventListener('click',openPicker);$$('.remove-product').forEach(b=>b.addEventListener('click',()=>{state.selected=state.selected.filter(x=>x.id!==b.dataset.id);render()}))}
function card(x){const metricKeys=x.type==='rubber'?['speed','spin','control']:['speed','control','weight'];const img=x.image?`<img class="product-image" src="${esc(x.image)}" alt="${esc(x.name)}" loading="lazy" onerror="this.outerHTML='<div class=\'product-image product-placeholder\'>${esc(x.brand.slice(0,2).toUpperCase())}</div>'">`:`<div class="product-image product-placeholder">${esc(x.brand.slice(0,2).toUpperCase())}</div>`;const metrics=metricKeys.map(k=>`<div class="metric"><div class="metric-head"><span>${labels[k].toUpperCase()}</span><b>${fmt(x.metrics[k])}${k==='weight'&&x.metrics[k]!=null?' g':''}</b></div>${segments(x.metrics[k],k,x.type)}</div>`).join('');let info=[];if(x.type==='rubber'){info=[['Typ',x.category],['Varianty',Object.values(x.variants).flat().length||'—']]}else{info=[['Kategória',x.category],['Rúčky',(x.variants['Rúčka']||[]).length||'—']]};return `<article class="product-card"><button class="remove-product" data-id="${x.id}" aria-label="Odstrániť">×</button><div class="product-brand">${esc(x.brand)}</div><h3 class="product-name">${esc(x.name)}</h3><div class="product-top">${img}<div class="status-stack">${x.inOffer?`<span class="offer-badge">V ponuke StoTen</span><span class="availability ${x.stock>0?'stock':''}">${esc(x.availability)}</span><div class="price">${money(x.price,x.currency)} <small>s DPH</small></div>`:`<span class="not-offer">Nie je vo verejnej ponuke</span>`}</div></div>${x.inOffer?`<a class="shop-link" href="${esc(x.url)}" target="_blank" rel="noopener">Zobraziť na StoTen.sk ↗</a>`:`<a class="shop-link" href="${esc(x.searchUrl)}" target="_blank" rel="noopener">Vyhľadať na StoTen.sk ↗</a>`}${metrics}<div class="card-foot">${info.map(i=>`<div class="mini-info"><span>${i[0]}</span><b>${esc(i[1])}</b></div>`).join('')}</div></article>`}
function renderRanking(){const box=$('#rankingChart');if(state.selected.length<2){box.innerHTML='<div class="empty-state">Pridajte aspoň dva produkty a zobrazí sa ranking.</div>';return}const sorted=[...state.selected].sort((a,b)=>score(b)-score(a));box.innerHTML=sorted.map((x,i)=>`<div class="rank-row"><span class="rank-number">${i+1}</span><span class="rank-name">${esc(x.name)}</span><div class="rank-track"><div class="rank-fill" style="width:${score(x)}%"></div></div><span class="rank-score">${score(x)}</span></div>`).join('')}
function renderTable(){const box=$('#comparisonTable');if(!state.selected.length){box.innerHTML='';return}const rows=state.type==='rubber'?[['speed','Rýchlosť'],['spin','Rotácia'],['control','Kontrola'],['price','Cena'],['availability','Dostupnosť'],['category','Typ']]:[['speed','Rýchlosť'],['control','Kontrola'],['weight','Hmotnosť'],['price','Cena'],['availability','Dostupnosť'],['category','Kategória']];let html='<table class="compare-table"><thead><tr><th>Parameter</th>'+state.selected.map(x=>`<th>${esc(x.brand)}<br><strong>${esc(x.name)}</strong></th>`).join('')+'</tr></thead><tbody>';for(const [key,label] of rows){const numeric=['speed','spin','control','weight','price'].includes(key);const vals=state.selected.map(x=>key==='price'?x.price:x.metrics[key]);const valid=vals.filter(v=>typeof v==='number');const best=valid.length?Math.max(...valid):null;html+=`<tr><td><span class="metric-label"><i class="metric-dot" style="background:${key==='speed'?'var(--red)':key==='spin'?'#33bdf7':key==='control'?'var(--green)':key==='weight'?'var(--violet)':'var(--cyan)'}"></i>${label}</span></td>`;state.selected.forEach((x,i)=>{let v;if(key==='price')v=x.inOffer?money(x.price,x.currency):'—';else if(key==='availability')v=x.inOffer?x.availability:'Nie je v ponuke';else if(key==='category')v=x.category;else v=fmt(x.metrics[key])+(key==='weight'&&x.metrics[key]!=null?' g':'');const isBest=numeric&&vals[i]!=null&&vals[i]===best;const pct=numeric&&key!=='price'&&vals[i]!=null?Math.min(100,vals[i]/max[state.type][key]*100):0;html+=`<td class="${isBest?'best-cell':''}">${esc(v)}${pct?`<div class="cell-bar"><i style="width:${pct}%"></i></div>`:''}</td>`});html+='</tr>'}html+='</tbody></table>';box.innerHTML=html}
function openPicker(){if(state.selected.length>=5)return;$('#picker').classList.add('open');$('#picker').setAttribute('aria-hidden','false');$('#searchInput').value='';renderPicker();setTimeout(()=>$('#searchInput').focus(),40)}function closePicker(){$('#picker').classList.remove('open');$('#picker').setAttribute('aria-hidden','true')}
function renderPicker(){const q=$('#searchInput').value.trim().toLowerCase();const offer=$('#offerOnly').checked;const selected=new Set(state.selected.map(x=>x.id));let list=all.filter(x=>x.type===state.type&&!selected.has(x.id)&&(!offer||x.inOffer)&&(q.length<1||x.name.toLowerCase().includes(q)||x.brand.toLowerCase().includes(q)));list.sort((a,b)=>(b.inOffer-a.inOffer)||a.name.localeCompare(b.name,'sk')).splice(80);$('#pickerResults').innerHTML=list.length?list.map(x=>`<button class="picker-item" data-id="${x.id}">${x.image?`<img class="picker-thumb" src="${esc(x.image)}" loading="lazy">`:`<div class="picker-thumb product-placeholder">${esc(x.brand.slice(0,2))}</div>`}<div><h3>${esc(x.name)}</h3><p>${esc(x.brand)} · ${esc(x.category)}</p></div><span class="picker-state">${x.inOffer?'V ponuke':'Katalóg'}</span></button>`).join(''):'<div class="empty-state">Nenašli sa žiadne produkty.</div>';$$('.picker-item').forEach(b=>b.addEventListener('click',()=>{const x=all.find(i=>i.id===b.dataset.id);if(x&&state.selected.length<5){state.selected.push(x);closePicker();render()}}))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
$$('.tab').forEach(t=>t.addEventListener('click',()=>{if(t.dataset.type===state.type)return;state.type=t.dataset.type;state.selected=[];const candidates=all.filter(i=>i.type===state.type&&i.inOffer).slice(0,2);state.selected=candidates;render()}));$$('[data-close]').forEach(x=>x.addEventListener('click',closePicker));$('#searchInput').addEventListener('input',renderPicker);$('#offerOnly').addEventListener('change',renderPicker);document.addEventListener('keydown',e=>{if(e.key==='Escape')closePicker()});$('#shareBtn').addEventListener('click',async()=>{syncUrl();try{await navigator.clipboard.writeText((window.STOTEN_PUBLIC_COMPARE_URL||location.href.split('?')[0])+location.search);toast('Odkaz na porovnanie je skopírovaný.')}catch{toast('Odkaz je pripravený v adresnom riadku.')}});params();render();
})();